version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: codemaker
    versions:
    - ">= 0"
  - dependency-name: "@jsii/*"
    versions:
    - ">= 0"
  - dependency-name: jsii*
    versions:
    - ">= 0"
  - dependency-name: "@types/node"
    versions:
    - ">=11.0.0-0"
  - dependency-name: aws-sdk
    versions:
    - 2.833.0
    - 2.834.0
    - 2.835.0
    - 2.836.0
    - 2.837.0
    - 2.838.0
    - 2.839.0
    - 2.840.0
    - 2.841.0
    - 2.842.0
    - 2.843.0
    - 2.844.0
    - 2.845.0
    - 2.846.0
    - 2.847.0
    - 2.848.0
    - 2.849.0
    - 2.850.0
    - 2.851.0
    - 2.853.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.857.0
    - 2.858.0
    - 2.859.0
    - 2.860.0
    - 2.861.0
    - 2.862.0
    - 2.863.0
    - 2.864.0
    - 2.865.0
    - 2.866.0
    - 2.867.0
    - 2.868.0
    - 2.869.0
    - 2.870.0
    - 2.871.0
    - 2.872.0
    - 2.873.0
    - 2.874.0
    - 2.875.0
    - 2.876.0
    - 2.877.0
    - 2.878.0
    - 2.879.0
    - 2.880.0
    - 2.881.0
    - 2.882.0
    - 2.883.0
    - 2.884.0
    - 2.885.0
    - 2.886.0
    - 2.887.0
    - 2.890.0
    - 2.891.0
    - 2.893.0
    - 2.894.0
  - dependency-name: parcel
    versions:
    - 2.0.0-nightly.554
    - 2.0.0-nightly.558
    - 2.0.0-nightly.560
    - 2.0.0-nightly.562
    - 2.0.0-nightly.566
    - 2.0.0-nightly.570
    - 2.0.0-nightly.573
    - 2.0.0-nightly.574
    - 2.0.0-nightly.577
    - 2.0.0-nightly.579
    - 2.0.0-nightly.585
    - 2.0.0-nightly.590
    - 2.0.0-nightly.592
    - 2.0.0-nightly.596
    - 2.0.0-nightly.597
    - 2.0.0-nightly.598
    - 2.0.0-nightly.600
    - 2.0.0-nightly.603
    - 2.0.0-nightly.605
    - 2.0.0-nightly.606
    - 2.0.0-nightly.607
    - 2.0.0-nightly.608
    - 2.0.0-nightly.609
    - 2.0.0-nightly.610
    - 2.0.0-nightly.614
    - 2.0.0-nightly.615
    - 2.0.0-nightly.618
    - 2.0.0-nightly.619
    - 2.0.0-nightly.620
    - 2.0.0-nightly.623
    - 2.0.0-nightly.625
    - 2.0.0-nightly.626
    - 2.0.0-nightly.628
    - 2.0.0-nightly.629
    - 2.0.0-nightly.630
    - 2.0.0-nightly.631
    - 2.0.0-nightly.632
    - 2.0.0-nightly.633
    - 2.0.0-nightly.634
    - 2.0.0-nightly.635
    - 2.0.0-nightly.636
    - 2.0.0-nightly.637
    - 2.0.0-nightly.639
    - 2.0.0-nightly.640
    - 2.0.0-nightly.641
    - 2.0.0-nightly.643
    - 2.0.0-nightly.644
  - dependency-name: table
    versions:
    - 6.0.7
    - 6.0.8
    - 6.0.9
    - 6.1.0
    - 6.3.0
    - 6.3.3
    - 6.3.4
    - 6.5.0
    - 6.5.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: fast-check
    versions:
    - 2.12.0
    - 2.12.1
    - 2.12.2
    - 2.13.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: "@types/table"
    versions:
    - 6.0.0
